oprations

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Naveen", "Vivek", "Asha"],
    "Marks": [85, 90, 78],
    "Age": [20, 21, 19]
})
df

     Name  Marks  Age
0  Naveen     85   20
1   Vivek     90   21
2    Asha     78   19

In [5]:
df.shape
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
 2   Age     3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [7]:
df.describe()

           Marks   Age
count   3.000000   3.0
mean   84.333333  20.0
std     6.027714   1.0
min    78.000000  19.0
25%    81.500000  19.5
50%    85.000000  20.0
75%    87.500000  20.5
max    90.000000  21.0

In [8]:
def square(x):
    return x**2

In [11]:
df["Age"]=df["Age"].apply(square)

In [12]:
df

     Name  Marks  Age
0  Naveen     85  400
1   Vivek     90  441
2    Asha     78  361